import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  icons: {
    icon: [
      {
        url: "/images/icon-on.svg",
        href: "/images/icon-on.svg",
      },
      {
        url: "/images/icon-off.svg",
        href: "/images/icon-off.svg",
      },
    ],
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className + "p-6"}>{children}</body>
    </html>
  );
}
